export function formatNumberWithCustomSuffix(value) {
    if (!isFinite(value)) {
        return "Infinity";
    } else if (value < 1) {
        return value.toFixed(1);
    }
    const suffixes = [
        "",
        "K",
        "M",
        "B",
        "T",
        "Qa",
        "Qi",
        "Sx",
        "Sp",
        "Oc",
        "No",
        "De",
        "UnD",
        "DuD",
        "TrD",
        "QaD",
        "QiD",
        "SeD",
        "SpD",
        "OcD",
        "NoD",
        "Vi",
        "UnV",
        "DuV",
        "TrV",
        "QaV",
        "QiV",
        "SeV",
        "SpV",
        "OcV",
        "NoV",
        "Ti",
        "UnT",
        "DuT",
        "TrT",
        "QaT",
        "QiT",
        "SeT",
        "SpT",
        "OcT",
        "NoT",
        "Go",
        "UnG",
        "DuG",
        "TrG",
        "QaG",
        "QiG",
        "SeG",
        "SpG",
        "OcG",
        "NoG",
        "Ge",
        "UnGe",
        "DuGe",
        "TrGe",
        "QaGe",
        "QiGe",
        "SeGe",
        "SpGe",
        "OcGe",
        "NoGe",
        "Ze",
        "UnZe",
        "DuZe",
        "TrZe",
        "QaZe",
        "QiZe",
        "SeZe",
        "SpZe",
        "OcZe",
        "NoZe",
        "Yi",
        "UnYi",
        "DuYi",
        "TrYi",
        "QaYi",
        "QiYi",
        "SeYi",
        "SpYi",
        "OcYi",
        "NoYi",
        "Xa",
        "UnXa",
        "DuXa",
        "TrXa",
        "QaXa",
        "QiXa",
        "SeXa",
        "SpXa",
        "OcXa",
        "NoXa",
        "Wk",
        "UnWk",
        "DuWk",
        "TrWk",
        "QaWk",
        "QiWk",
        "SeWk",
        "SpWk",
        "OcWk",
        "NoWk",
        "Yn",
    ];
    const powersOfTen = Math.floor(Math.log10(Math.abs(value)) / 3);
    const scaledValue = value / Math.pow(10, powersOfTen * 3);
    const suffix = suffixes[powersOfTen];

    const numberFormat = new Intl.NumberFormat("en", {
        minimumFractionDigits: 1,
        maximumFractionDigits: 2,
    });

    const formattedValue = numberFormat.format(scaledValue);

    return `${formattedValue} ${suffix}`;
}